#!/bin/bash
# `announce` can be used by a host that wants to become reachable via name lookup. The hosts determines its own IP address
# on the network and then updates the registry with an HTTP request to the web endpoint of the pocket-dns redis back-end.

REGISTRY="http://pocket-dns:6380"
ADDR_PREFIX="192.168.178"  # TODO: this is kinda rough

function die() {
  echo "error: $1"
  exit 1
}

function check_deps() {
  me=$(basename "$0")
  for var in "$@"; do
    which "${var}" &>/dev/null || die "${me} requires ${var}"
  done
}

# verify all these programs are available
check_deps hostname ip grep awk sed curl jq

## main
HOST=$(hostname)
ADDR=$(ip a | grep inet | grep "${ADDR_PREFIX}" | awk '{ print $2 }' | sed -E 's/\/\S+//')

[[ $(curl --silent "${REGISTRY}/set/${HOST}/${ADDR}" | jq -r '.set[1]') != "OK" ]] && die "could not update the registry"
echo "success: new IP for ${HOST} is ${ADDR}"
